export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";

export const CART_CLEAR_ITEM = "CART_CLEAR_ITEM";
