export const ALL_QRCODE_REQUEST = "ALL_QRCODE_REQUEST";
export const ALL_QRCODE_SUCCESS = "ALL_QRCODE_SUCCESS";
export const ALL_QRCODE_FAIL = "ALL_QRCODE_FAIL";

export const ADMIN_QRCODE_REQUEST = "ADMIN_QRCODE_REQUEST";
export const ADMIN_QRCODE_SUCCESS = "ADMIN_QRCODE_SUCCESS";
export const ADMIN_QRCODE_FAIL = "ADMIN_QRCODE_FAIL";

export const NEW_QRCODE_REQUEST = "NEW_QRCODE_REQUEST";
export const NEW_QRCODE_SUCCESS = "NEW_QRCODE_SUCCESS";
export const NEW_QRCODE_RESET = "NEW_QRCODE_RESET";
export const NEW_QRCODE_FAIL = "NEW_QRCODE_FAIL";

export const UPDATE_QRCODE_REQUEST = "UPDATE_QRCODE_REQUEST";
export const UPDATE_QRCODE_SUCCESS = "UPDATE_QRCODE_SUCCESS";
export const UPDATE_QRCODE_RESET = "UPDATE_QRCODE_RESET";
export const UPDATE_QRCODE_FAIL = "UPDATE_QRCODE_FAIL";

export const DELETE_QRCODE_REQUEST = "DELETE_QRCODE_REQUEST";
export const DELETE_QRCODE_SUCCESS = "DELETE_QRCODE_SUCCESS";
export const DELETE_QRCODE_RESET = "DELETE_QRCODE_RESET";
export const DELETE_QRCODE_FAIL = "DELETE_QRCODE_FAIL";

export const QRCODE_DETAILS_REQUEST = "QRCODE_DETAILS_REQUEST";
export const QRCODE_DETAILS_SUCCESS = "QRCODE_DETAILS_SUCCESS";
export const QRCODE_DETAILS_FAIL = "QRCODE_DETAILS_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";